### PR TITLE
fixed #30 - wrong use of variable variables on big endian

### LINKED ISSUE #30: Test failure on big endian
We encounter erratic failure on this library test suite in Fedora QA.
https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-serializer?collection=f28

Test suite passes on littleendian (x86_64, ppc64le, ...)
Test suite fails on bugendian (s390x...)

```
There were 3 errors:
1) ZendTest\Serializer\Adapter\PythonPickleUnserializeTest::testUnserializeLong4Positive
Undefined variable: 
/builddir/build/BUILDROOT/php-zendframework-zend-serializer-2.8.0-3.fc28.noarch/usr/share/php/Zend/Serializer/Adapter/PythonPickle.php:914
/builddir/build/BUILDROOT/php-zendframework-zend-serializer-2.8.0-3.fc28.noarch/usr/share/php/Zend/Serializer/Adapter/PythonPickle.php:636
/builddir/build/BUILDROOT/php-zendframework-zend-serializer-2.8.0-3.fc28.noarch/usr/share/php/Zend/Serializer/Adapter/PythonPickle.php:554
/builddir/build/BUILD/zend-serializer-ff74ea020f5f90866eb28365327e9bc765a61a6e/test/Adapter/PythonPickleUnserializeTest.php:141
2) ZendTest\Serializer\Adapter\PythonPickleUnserializeTest::testUnserializeLong4Negative
Undefined variable: 
/builddir/build/BUILDROOT/php-zendframework-zend-serializer-2.8.0-3.fc28.noarch/usr/share/php/Zend/Serializer/Adapter/PythonPickle.php:914
/builddir/build/BUILDROOT/php-zendframework-zend-serializer-2.8.0-3.fc28.noarch/usr/share/php/Zend/Serializer/Adapter/PythonPickle.php:636
/builddir/build/BUILDROOT/php-zendframework-zend-serializer-2.8.0-3.fc28.noarch/usr/share/php/Zend/Serializer/Adapter/PythonPickle.php:554
/builddir/build/BUILD/zend-serializer-ff74ea020f5f90866eb28365327e9bc765a61a6e/test/Adapter/PythonPickleUnserializeTest.php:152
3) ZendTest\Serializer\Adapter\PythonPickleUnserializeTest::testUnserializeLong4BigInt
Undefined variable: 
/builddir/build/BUILDROOT/php-zendframework-zend-serializer-2.8.0-3.fc28.noarch/usr/share/php/Zend/Serializer/Adapter/PythonPickle.php:914
/builddir/build/BUILDROOT/php-zendframework-zend-serializer-2.8.0-3.fc28.noarch/usr/share/php/Zend/Serializer/Adapter/PythonPickle.php:636
/builddir/build/BUILDROOT/php-zendframework-zend-serializer-2.8.0-3.fc28.noarch/usr/share/php/Zend/Serializer/Adapter/PythonPickle.php:554
/builddir/build/BUILD/zend-serializer-ff74ea020f5f90866eb28365327e9bc765a61a6e/test/Adapter/PythonPickleUnserializeTest.php:163
```

### PR DESCRIPTION
**Pull request by marc-mabe**
fixes #30 

@remicollet please check if that fixes the issue - thanks

### CODE REVIEW

**Comment by remicollet** [comment]
@marc-mabe sorry for not being able to test this PR yet (terribly busy with release week)
Should be able to give you some feedback before end of week

**Comment by remicollet** [comment]
Still failing on bigendian

```
+ php /usr/bin/phpunit
PHPUnit 5.7.23 by Sebastian Bergmann and contributors.
SSSSSSSSSSS.............SSSSSSSSSSSS.........................S.  63 / 185 ( 34%)
.....................................................F......... 126 / 185 ( 68%)
...........................................................     185 / 185 (100%)
Time: 88 ms, Memory: 6.00MB
There was 1 failure:
1) ZendTest\Serializer\Adapter\PythonPickleUnserializeTest::testUnserializeLong4BigInt
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'-6944656592455360768'
+'44930029223649183'
/builddir/build/BUILD/zend-serializer-ff74ea020f5f90866eb28365327e9bc765a61a6e/test/Adapter/PythonPickleUnserializeTest.php:164
FAILURES!
```

See Fedora scratch build for various archictectures:
https://koji.fedoraproject.org/koji/taskinfo?taskID=22988940

Failing on ppc64 and s390x (both bigendian)

**Comment by marc-mabe** [comment]
@remicollet I'm very happy to have you testing this :+1:
-> Please try again

**Comment by remicollet** [comment]
New Fedora scratch build
https://koji.fedoraproject.org/koji/taskinfo?taskID=23007185

The test suite passes on all arch  \o/

Thanks

**Comment by marc-mabe** [comment]
Closed as not an issue anymore

**Pull request merged**
