### PR TITLE
bump minimum php version to 5.5

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by marc-mabe** [comment]
@weierophinney Is this required if there is no code change ?

**Comment by samsonasik** [comment]
the codes are using short array syntax, so current requirement should be updated.

Warm regards,

Abdul Malik Ikhsan

Pada 19 Jun 2015, pukul 12.01, Marc Bennewitz notifications@github.com menulis:

**Comment by marc-mabe** [comment]
Oh I See! The Version bumb was missed on introducing this.

So this is a bug fix :)

**Comment by Maks3w** [comment]
@marc-mabe This PR does not fix nothing.

**Comment by marc-mabe** [comment]
@Maks3w Without the version bump the minimum required version of this component stand on an incompatible one noted by composer. Sure it's not a bug of the code but it is indeed a bug of documentation for composer. As of this wasn't released yet it's also not a bug of any release and doesn't need to be noted in the changelog but from the point of having the master stable all the time it's a bug of the current master.

Please correct me if it's a wrong perception.

**Comment by Maks3w** [comment]
version bump is already done

**Comment by weierophinney** [comment]
Closing; version updated in a1b642a.

**Comment by harikt** [comment]
Is there a reason why PR's are not merged ?

Looking at commit https://github.com/zendframework/zend-serializer/commit/a1b642ab721f3634798cc5ad3f8facd66b8f20de it looks 18 days old. But this PR is 19 days old.

**Comment by samsonasik** [comment]
@harikt I _did_ sent PRs for it in all components 19 days ago, but it seems, 18 days ago the commit by @Maks3w dramatically push to all components, so I need to close them all ... or... do cherry-pick because some my PRs change _not only_ change the minimum php version, but the apply PHP 5.4 and 5.5 features.

**Pull request closed without merging**
